name: FastAPI - Sync to Hugging Face
on:
  push:
    paths:
      - 'FastAPI/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          mkdir tmp
          cp -r FastAPI/* tmp/
          cd tmp

          git init
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add .
          git commit -m "Deploy to Hugging Face"

          git branch -m master main

          git remote add hf "https://lyx51:${HF_TOKEN}@huggingface.co/spaces/lyx51/Fraud-detection-FastAPI"
          git fetch hf
          git push hf main:main --force